# Summary
* [Test](test/README.md)
    * [Chapter 1](test/chapter1.md)
    * [Chapter 2](test/chapter2.md)
* [Part I](part1/README.md)
    * [Writing is nice](part1/writing.md)
    * [GitBook is nice](part1/gitbook.md)
* [Part II](part2/README.md)
    * [We love feedback](part2/feedback_please.md)
    * [Better tools for authors](part2/better_tools.md)